
services:
  backend:
    build: ./backend
    container_name: arbitro_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - DOCKER_MODE=true
    restart: always

  frontend:
    build: ./vue-arbitro
    container_name: arbitro_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./vue-arbitro:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend #always start backend before frontend
    restart: always